*DECK MPUNFL
      SUBROUTINE MPUNFL (X)
C***BEGIN PROLOGUE  MPUNFL
C***SUBSIDIARY
C***PURPOSE  Subsidiary to DQDOTA and DQDOTI
C***LIBRARY   SLATEC
C***TYPE      ALL (MPUNFL-A)
C***AUTHOR  (UNKNOWN)
C***DESCRIPTION
C
C Called on multiple-precision underflow, i.e.  when the
C exponent of 'mp' number X would be less than -M.
C
C***SEE ALSO  DQDOTA, DQDOTI
C***ROUTINES CALLED  MPCHK
C***REVISION HISTORY  (YYMMDD)
C   791001  DATE WRITTEN
C   890831  Modified array declarations.  (WRB)
C   891214  Prologue converted to Version 4.0 format.  (BAB)
C   900402  Added TYPE section.  (WRB)
C***END PROLOGUE  MPUNFL
      INTEGER X(*)
C***FIRST EXECUTABLE STATEMENT  MPUNFL
      CALL MPCHK (1, 4)
C THE UNDERFLOWING NUMBER IS SET TO ZERO
C AN ALTERNATIVE WOULD BE TO CALL MPMINR (X) AND RETURN,
C POSSIBLY UPDATING A COUNTER AND TERMINATING EXECUTION
C AFTER A PRESET NUMBER OF UNDERFLOWS.  ACTION COULD EASILY
C BE DETERMINED BY A FLAG IN LABELLED COMMON.
      X(1) = 0
      RETURN
      END
